### ISSUE TITLE
Updated instructions for loading the tag library

### ISSUE THREAD

**Issue by amitmodi06** [dostogircse171/django_events_timetable#25]
Currently following it the Loading Template Tags instructions in the README file:
`{% load display_event %}`

It should be:
`{% load display_events_tag %}`

Also the occurrence of work "Group" is replaced with "Event" as per the new code update.

**Comment by dostogircse171** [comment]
Yes, you are right we need to update it. Do you want me to do it or you will do it?

**Comment by amitmodi06** [comment]
I've worked on it. Will be raising a PR soon.
