### ISSUE TITLE
Under display_event tag is_negative need to initialise 

### ISSUE THREAD

**Issue by dostogircse171** [dostogircse171/django_events_timetable#40]
There is a **UnboundLocalError** occurring when no data in the model and calling the tags because the variable **is_negative** is being referenced before it has been assigned. if neither if nor else conditions where **is_negative** is set are met, then **is_negative** will not be defined as it's getting a None value.

Need to initialize **_is_negative = False_** before **_try_** block. 

**Test Case:
Try removing all events and items and you will see the error.**

**Comment by amitmodi06** [comment]
It's a nice catch. Thanks for raising the issue.
